{
 "title": "Ceph Cluster Dashboard",
 "description": "Provided by OpenNext SAS",
 "tags": [
  "ceph",
  "influxdb",
  "telegraf",
  "opennext"
 ],
 "time": { "from": "now-1h", "to": "now-60s" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "pool",
    "label": "Ceph Pools",
    "query": "SHOW TAG VALUES FROM \"ceph_pool_usage\" WITH KEY = \"name\""
   }
  ]
 },
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Monitors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"num_mon\") FROM \"ceph\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Monitors Quorum",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"num_mon_quorum\") FROM \"ceph\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Pools",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"num_pool\") FROM \"ceph\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cluster Available Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"total_avail_bytes\") FROM \"ceph_usage\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cluster Used Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"total_used_bytes\") FROM \"ceph_usage\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Placement Groups",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"num_pg\") FROM \"ceph\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Objects",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"num_object\") FROM \"ceph\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OSDs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(\"num_osds\") from \"ceph_osdmap\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OSDs IN",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(\"num_in_osds\") from \"ceph_osdmap\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OSDs UP",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(\"num_up_osds\") from \"ceph_osdmap\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OSDs DOWN",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(\"num_osds\") - last(\"num_up_osds\") from \"ceph_osdmap\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cluster Used Percent",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (last(\"total_used_bytes\") / last(\"total_avail_bytes\")) * 100 FROM \"ceph_usage\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Degraded Objects",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "measurement": "ceph_pgmap",
     "query": "SELECT  (last(\"num_object_degraded\") / last(\"num_object\")) * 100 FROM \"ceph\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "degraded_ratio" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Misplaced Objects",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "measurement": "ceph_pgmap",
     "query": "SELECT  (last(\"num_object_misplaced\") / last(\"num_object\")) * 100 FROM \"ceph\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "misplaced_ratio" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {}
   ]
  },
  {
   "title": "Full OSDs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"full\") FROM \"ceph_osdmap\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Near Full OSDs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"nearfull\") FROM \"ceph_osdmap\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Objects Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Objects by state",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "ceph_pgmap",
       "query": "SELECT  mean(\"num_object\") AS \"Total\" FROM \"ceph\" WHERE $timeFilter GROUP BY time($interval)",
       "select": [
        [
         { "params": [ "degraded_objects" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "ceph_pgmap",
       "query": "SELECT  mean(\"num_object_degraded\") AS \"Degraded\" FROM \"ceph\" WHERE $timeFilter GROUP BY time($interval)",
       "select": [
        [
         { "params": [ "degraded_objects" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "ceph_pgmap",
       "query": "SELECT  mean(\"num_object_misplaced\") AS \"Misplaced\" FROM \"ceph\" WHERE $timeFilter GROUP BY time($interval)",
       "select": [
        [
         { "params": [ "degraded_objects" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "ceph_pgmap",
       "query": "SELECT  mean(\"num_object_unfound\") AS \"Unfound\" FROM \"ceph\" WHERE $timeFilter GROUP BY time($interval)",
       "select": [
        [
         { "params": [ "degraded_objects" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Placement Groups Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "PGs IOPs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "iops", "label": "read / write IOPs" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "ceph_pool_stats",
       "query": "SELECT mean(\"read_op_per_sec\") AS \"Read IOPs\" FROM \"ceph_pgmap\" WHERE  $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "read_op_per_sec" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         },
         { "params": [ "read" ], "type": "alias" }
        ],
        [
         { "params": [ "write_op_per_sec" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$pool$/" }
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "ceph_pool_stats",
       "query": "SELECT mean(\"write_op_per_sec\") AS \"Write IOPs\" FROM \"ceph_pgmap\" WHERE  $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "read_op_per_sec" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         },
         { "params": [ "read" ], "type": "alias" }
        ],
        [
         { "params": [ "write_op_per_sec" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$pool$/" }
       ]
      }
     ]
    },
    {
     "title": "PGs IOs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "Bps", "label": "read / write bytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "ceph_pool_stats",
       "query": "SELECT mean(\"read_bytes_sec\") AS \"Read bytes sec\" FROM \"ceph_pgmap\" WHERE  $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "read_op_per_sec" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         },
         { "params": [ "read" ], "type": "alias" }
        ],
        [
         { "params": [ "write_op_per_sec" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$pool$/" }
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "ceph_pool_stats",
       "query": "SELECT mean(\"write_bytes_sec\") AS \"Write bytes sec\" FROM \"ceph_pgmap\" WHERE  $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "read_op_per_sec" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         },
         { "params": [ "read" ], "type": "alias" }
        ],
        [
         { "params": [ "write_op_per_sec" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$pool$/" }
       ]
      }
     ]
    },
    {
     "title": "Placement Groups by State",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"num_pg\") AS \"Total\" FROM \"ceph\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_state",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"count\") FROM \"ceph_pgmap_state\" WHERE $timeFilter GROUP BY time($interval), \"state\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Pools Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Pools IOPs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "iops", "label": "read / writes IOPs" }
   ],
   "targets": [
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ceph_pool_stats",
     "query": "SELECT mean(\"read_op_per_sec\") AS \"Read IOPs\" FROM \"ceph_pool_stats\" WHERE   \"name\" =~ /^$pool$/ AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "read_op_per_sec" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "write_op_per_sec" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$pool$/" }
     ]
    },
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ceph_pool_stats",
     "query": "SELECT mean( \"write_op_per_sec\") AS \"Write IOPs\" FROM \"ceph_pool_stats\" WHERE \"name\" =~ /^$pool$/ AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "read_op_per_sec" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "write_op_per_sec" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Pools IOs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "iops", "label": "read / write bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ceph_pool_stats",
     "query": "SELECT mean(\"read_bytes_sec\") AS \"Read bytes\" FROM \"ceph_pool_stats\" WHERE \"name\" =~ /^$pool$/  AND  $timeFilter GROUP BY time($interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "read_op_per_sec" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "write_op_per_sec" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$pool$/" }
     ]
    },
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ceph_pool_stats",
     "query": "SELECT mean( \"write_bytes_sec\") AS \"Write bytes\" FROM \"ceph_pool_stats\" WHERE \"name\" =~ /^$pool$/ AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "read_op_per_sec" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "write_op_per_sec" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Pools Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ceph_pool_usage",
     "query": "SELECT mean(\"bytes_used\") AS \"Used\", mean(\"max_avail\") AS \"Available\" FROM \"ceph_pool_usage\" WHERE \"name\" =~ /^$pool$/ AND $timeFilter GROUP BY time($interval), \"name\" fill(none)",
     "select": [
      [
       { "params": [ "bytes_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "max_avail" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "available" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Pools Usage Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ceph_pool_usage",
     "query": "SELECT mean(\"percent_used\") AS \"Percent used\" FROM \"ceph_pool_usage\" WHERE \"name\" =~ /^$pool$/ AND $timeFilter GROUP BY time($interval), \"name\" fill(none)",
     "select": [
      [
       { "params": [ "bytes_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "max_avail" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "available" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Pools Usage by Objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name: $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ceph_pool_usage",
     "query": "SELECT mean(\"objects\") AS \"Objects\" FROM \"ceph_pool_usage\" WHERE (\"name\" =~ /^$pool$/) AND $timeFilter GROUP BY time($interval), \"name\" fill(none)",
     "select": [
      [
       { "params": [ "bytes_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "max_avail" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "available" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$pool$/" }
     ]
    }
   ]
  },
  {
   "title": "Recovery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Recovery Objects",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_name: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "ceph_pool_stats",
       "query": "SELECT mean(\"recovering_objects_per_sec\") AS \"Recovering objects\" FROM \"ceph_pool_stats\" WHERE  $timeFilter GROUP BY time($interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "recovering_objects_per_sec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "objects" ], "type": "alias" }
        ],
        [
         { "params": [ "recovering_keys_per_sec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "keys" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$pool$/" }
       ]
      }
     ]
    },
    {
     "title": "Recovery Bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_name: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "ceph_pool_stats",
       "query": "SELECT mean(\"recovering_bytes_per_sec\") AS \"Recovering bytes\" FROM \"ceph_pool_stats\" WHERE  $timeFilter GROUP BY time($interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "recovering_objects_per_sec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "objects" ], "type": "alias" }
        ],
        [
         { "params": [ "recovering_keys_per_sec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "keys" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$pool$/" }
       ]
      }
     ]
    },
    {
     "title": "Recovery Keys",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$tag_name: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "ceph_pool_stats",
       "query": "SELECT mean(\"recovering_keys_per_sec\") AS \"Recovering keys\" FROM \"ceph_pool_stats\" WHERE  $timeFilter GROUP BY time($interval), \"name\" fill(null)",
       "select": [
        [
         { "params": [ "recovering_objects_per_sec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "objects" ], "type": "alias" }
        ],
        [
         { "params": [ "recovering_keys_per_sec" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "keys" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=~", "value": "/^$pool$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latencies",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_collection: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"refresh_latency.avgtime\") AS \"Refresh\" FROM \"ceph\" WHERE $timeFilter GROUP BY time($interval), \"collection\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_collection: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"begin_latency.avgtime\") AS \"Begin\" FROM \"ceph\" WHERE $timeFilter GROUP BY time($interval), \"collection\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_collection: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"collect_latency.avgtime\") AS \"Collect\" FROM \"ceph\" WHERE $timeFilter GROUP BY time($interval), \"collection\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_collection: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"commit_latency.avgtime\") AS \"Commit\" FROM \"ceph\" WHERE $timeFilter GROUP BY time($interval), \"collection\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_collection: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"new_pn_latency.avgtime\") AS \"New PN\" FROM \"ceph\" WHERE $timeFilter GROUP BY time($interval), \"collection\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_collection: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"get_latency.avgtime\") AS \"Get\" FROM \"ceph\" WHERE $timeFilter GROUP BY time($interval), \"collection\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_collection: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"complete_latency.avgtime\") AS \"Complete\" FROM \"ceph\" WHERE $timeFilter GROUP BY time($interval), \"collection\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_collection: $col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"store_state__latency.avgtime\") AS \"Store state\" FROM \"ceph\" WHERE $timeFilter GROUP BY time($interval), \"collection\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}