{
 "title": "HAProxy Metrics",
 "description": "HAProxy runtime metrics",
 "tags": [
  "haproxy",
  "influxdb",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now-10s" },
 "refresh": "20s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Hosts",
    "query": "SHOW TAG VALUES FROM \"haproxy\" WITH KEY = \"host\""
   },
   {
    "name": "frontend",
    "label": "Frontends",
    "query": "SHOW TAG VALUES FROM \"haproxy\" WITH KEY = \"proxy\""
   },
   {
    "name": "backend",
    "label": "Backends",
    "query": "SHOW TAG VALUES FROM \"haproxy\" WITH KEY = \"proxy\""
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "10s, 30s, 1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "General Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backend HTTP errors rate",
   "type": "singlestat",
   "description": "HTTP 5xx request errors 1 minute rate of change over the last 15 minutes",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(mean(\"http_response.5xx\")) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'backend' AND \"instance\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Backend connections waiting",
   "type": "singlestat",
   "description": "Number of connections awaiting assignment to a backend server over the last 15 minutes",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"qcur\") FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'backend' AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of backends in error",
   "type": "singlestat",
   "description": "Number of backend which status is different than 'UP'",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"noup\") FROM (SELECT last(\"status\") as \"noup\" FROM \"haproxy\" WHERE \"type\" = 'server' AND \"status\" !~ /UP/ AND $timeFilter GROUP BY \"sv\", \"proxy\") fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average requests queue time",
   "type": "singlestat",
   "description": "The average requests queue time 1 minute derivative over the last 15 minutes.",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"qtime\") FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'backend' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Frontend requests errors rate",
   "type": "singlestat",
   "description": "Frontend requests errors 1m rate of change over the last15 minutes.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"ereq\")) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'frontend' AND \"proxy\" =~ /^$frontend$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Frontend denied requests rate",
   "type": "singlestat",
   "description": "Frontend denied requests 1m rate of change over the last 15 minutes.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"dreq\")) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'frontend' AND \"proxy\" =~ /^$frontend$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of frontend in error",
   "type": "singlestat",
   "description": "Number of frontends which status is different than 'OPEN'",
   "gridPos": { "h": 3, "w": 5, "x": 8, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"noup\") FROM (SELECT last(status) as \"noup\" FROM \"haproxy\" WHERE \"type\" = 'frontend' AND \"status\" != 'OPEN' AND $timeFilter GROUP BY \"proxy\", \"host\") fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Frontend Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Sessions usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_proxy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ((mean(\"scur\") / mean(\"slim\")) * 100) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'frontend' AND $timeFilter GROUP BY time($interval), \"proxy\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sessions rate",
   "type": "graph",
   "description": "Number of sessions created per second",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_proxy",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT mean(\"rate\") FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$frontend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP requests rate",
   "type": "graph",
   "description": "Number of HTTP requests / sec",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_proxy",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT mean(\"req_rate\") FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$frontend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
     "select": [
      [
       { "params": [ "req_rate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "Bytes received rate",
   "type": "graph",
   "description": "Number of bytes received / sec",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_proxy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(last(\"bin\")) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$frontend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Frontends Current Status",
   "type": "table",
   "description": "A status different than 'OPEN' should be acted upon",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"frontend\", \"status\", \"host\" FROM (SELECT last(status) as \"status\", \"proxy\" as \"frontend\", \"sv\" as \"sv\", \"host\" as \"host\" FROM \"haproxy\" WHERE \"type\" = 'frontend' AND $timeFilter AND \"host\" =~ /^$host$/ GROUP BY \"host\", \"proxy\" fill(null))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Requests denied rate",
   "type": "graph",
   "description": "Requests denied because of security concerns.\n- For tcp this is because of a matched tcp\n  request content rule.\n- For http this is because of a matched http\n  request or tarpit rule.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_proxy",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT derivative(mean(\"dreq\")) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'frontend' AND $timeFilter GROUP BY time($interval), \"proxy\" fill(null)",
     "select": [
      [
       { "params": [ "ereq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP responses",
   "type": "graph",
   "description": "Number of HTTP responses / sec",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col: $tag_proxy",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT derivative(last(\"http_response.1xx\")) AS \"http 1xx\" FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$frontend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
     "select": [
      [
       { "params": [ "ereq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    },
    {
     "alias": "$col: $tag_proxy",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT derivative(last(\"http_response.2xx\")) AS \"http 2xx\" FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$frontend$/ AND $timeFilter GROUP BY time($interval), \"proxy\" ",
     "select": [
      [
       { "params": [ "ereq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    },
    {
     "alias": "$col: $tag_proxy",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT derivative(last(\"http_response.3xx\")) AS \"http 3xx\" FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$frontend$/ AND $timeFilter GROUP BY time($interval), \"proxy\" ",
     "select": [
      [
       { "params": [ "ereq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    },
    {
     "alias": "$col: $tag_proxy",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT derivative(last(\"http_response.4xx\")) AS \"http 4xx\" FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$frontend$/ AND $timeFilter GROUP BY time($interval), \"proxy\" ",
     "select": [
      [
       { "params": [ "ereq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    },
    {
     "alias": "$col: $tag_proxy",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT derivative(last(\"http_response.5xx\")) AS \"http 5xx\" FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$frontend$/ AND $timeFilter GROUP BY time($interval), \"proxy\" ",
     "select": [
      [
       { "params": [ "ereq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "Requests errors rate",
   "type": "graph",
   "description": "Request errors. Some of the possible causes are:\n- early termination from the client, before the\n  request has been sent.\n- read error from the client\n   - client timeout\n   - client closed connection\n   - various bad requests from the client.\n   - request was tarpitted.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_proxy",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT derivative(mean(\"ereq\")) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"type\" = 'frontend' AND $timeFilter GROUP BY time($interval), \"proxy\" ",
     "select": [
      [
       { "params": [ "ereq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "Bytes sent rate",
   "type": "graph",
   "description": "Number of bytes sent  /sec",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_proxy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(last(\"bout\")) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$frontend$/ AND $timeFilter GROUP BY time($interval), \"proxy\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Backend Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Backends Current Status",
   "type": "table",
   "description": "A status different than 'UP' should be acted upon",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"proxy\", \"status\", \"check_status\", \"sv\"  FROM (SELECT last(status) as \"status\", \"proxy\" as \"proxy\", \"check_status\" as \"check_status\", \"sv\" as \"sv\" FROM \"haproxy\" WHERE \"type\" = 'server'  AND $timeFilter AND \"host\" =~ /^$host$/ GROUP BY \"sv\", \"proxy\" fill(null))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Byes received rate",
   "type": "graph",
   "description": "Number of bytes received by the backends / sec",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_proxy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(last(\"bin\")) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sessions usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_proxy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ((mean(\"scur\") / mean(\"slim\")) * 100) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND  \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "description": "Average backend response time (in ms) for the last 1,024 requests",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_proxy",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT mean(\"rtime\") FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
     "select": [
      [
       { "params": [ "rtime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "HTTP responses rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col: $tag_proxy",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT derivative(last(\"http_response.1xx\")) AS \"http 1xx\" FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
     "select": [
      [
       { "params": [ "ereq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    },
    {
     "alias": "$col: $tag_proxy",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT derivative(last(\"http_response.2xx\")) AS \"http 2xx\" FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
     "select": [
      [
       { "params": [ "ereq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    },
    {
     "alias": "$col: $tag_proxy",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT derivative(last(\"http_response.3xx\")) AS \"http 3xx\" FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
     "select": [
      [
       { "params": [ "ereq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    },
    {
     "alias": "$col: $tag_proxy",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT derivative(last(\"http_response.4xx\")) AS \"http 4xx\" FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
     "select": [
      [
       { "params": [ "ereq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    },
    {
     "alias": "$col: $tag_proxy",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT derivative(last(\"http_response.5xx\")) AS \"http 5xx\" FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
     "select": [
      [
       { "params": [ "ereq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "Average queue time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_proxy",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT mean(\"qtime\") FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
     "select": [
      [
       { "params": [ "qtime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend connection retries rate",
   "type": "graph",
   "description": "Number of times a connection was retried",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_proxy",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT non_negative_derivative(mean(\"wretr\")) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
     "select": [
      [
       { "params": [ "eresp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "Average queue size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_proxy",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT mean(\"qcur\") FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\" fill(null)",
     "select": [
      [
       { "params": [ "qtime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend redispatchs rate",
   "type": "graph",
   "description": "Number of times a request was redispatched to a different backend",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_proxy",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT non_negative_derivative(mean(\"wredis\")) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
     "select": [
      [
       { "params": [ "eresp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "Backend requests errors rate",
   "type": "graph",
   "description": "Number of requests that encountered an error attempting to connect to a backend server",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_proxy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"econ\")) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Backend failed requests rate",
   "type": "graph",
   "description": "Rate of requests whose responses yielded an error",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_proxy",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT non_negative_derivative(mean(\"eresp\")) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\" fill(null)",
     "select": [
      [
       { "params": [ "eresp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "Bytes sent rate",
   "type": "graph",
   "description": "Number of bytes sent / sec by the backends",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_proxy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"bout\")) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Backend responses denied rate",
   "type": "graph",
   "description": "Responses denied due to security raisons (ACL-restricted)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_proxy",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT non_negative_derivative(mean(\"dresp\")) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\" fill(null)",
     "select": [
      [
       { "params": [ "econ" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of requests unassigned",
   "type": "graph",
   "description": "Current number of requests unassigned in queue",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_proxy",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "proxy" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "haproxy",
     "options": {
      "showDisabledItems": false
     },
     "query": "SELECT mean(\"qcur\") FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\" fill(null)",
     "select": [
      [
       { "params": [ "qtime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
      { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
     ]
    }
   ]
  }
 ]
}