{
 "title": "InfluxDB Metrics",
 "description": "metrics on influxdb from telegraf",
 "tags": [ "influxdb" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "database",
    "label": "Database",
    "query": "SHOW TAG VALUES FROM \"influxdb_database\" WITH KEY = \"database\""
   }
  ]
 },
 "panels": [
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Queries",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "query": "SELECT non_negative_derivative(last(\"queryReq\"), 1s) FROM \"influxdb_httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "queryReq" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Client Errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "query": "SELECT non_negative_derivative(last(\"clientError\"), 1s) FROM \"influxdb_httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "clientError" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Server Errors",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "query": "SELECT non_negative_derivative(last(\"serverError\"), 1s) FROM \"influxdb_httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "serverError" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Points",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Write Fail",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "query": "SELECT non_negative_derivative(last(\"pointsWrittenFail\"), 1s) FROM \"influxdb_httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "pointsWrittenFail" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    },
    {
     "alias": "Write OK",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "httpd",
     "query": "SELECT non_negative_derivative(last(\"pointsWrittenOK\"), 1s) FROM \"influxdb_httpd\" WHERE $timeFilter GROUP BY time($interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "pointsWrittenOK" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Number of Series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Number of Series: $database",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "database",
     "query": "SELECT last(\"numSeries\") FROM \"influxdb_database\" WHERE \"database\" =~ /^$database$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "numSeries" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Measurements",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Number of Measurements: $database",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"numMeasurements\") FROM \"influxdb_database\" WHERE \"database\" =~ /^$database$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Sys",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "query": "SELECT mean(\"Sys\") FROM \"influxdb_runtime\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total Alloc",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "runtime",
     "query": "SELECT mean(\"TotalAlloc\") FROM \"influxdb_runtime\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}