{
 "title": "Swift Proxy Server Metrics",
 "description": "Swift Object Storage runtime metrics",
 "tags": [
  "opennext",
  "swift",
  "telegraf",
  "influxdb"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Proxy Server - Account", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GET Count HTTP 200 per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "swift.proxy-server.account",
     "query": "SELECT mean(\"timing_count\") FROM \"swift.proxy-server.account\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'GET' AND \"returncode\" = '200' AND $timeFilter GROUP BY \"host\", time($interval) fill(null)",
     "select": [
      [
       { "params": [ "timing_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "method", "operator": "=", "value": "GET" },
      { "condition": "AND", "key": "returncode", "operator": "=", "value": "200" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "counter" }
     ]
    }
   ]
  },
  {
   "title": "HEAD Count HTTP 204 per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swift.proxy-server.account",
     "query": "SELECT mean(\"timing_count\") FROM \"swift.proxy-server.account\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'HEAD' AND \"returncode\" = '204' AND $timeFilter GROUP BY \"host\", time($interval) fill(null)",
     "select": [
      [
       { "params": [ "timing_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "method", "operator": "=", "value": "HEAD" },
      { "condition": "AND", "key": "returncode", "operator": "=", "value": "204" }
     ]
    }
   ]
  },
  { "title": "Proxy Server - Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "GET Count HTTP 200 and 204 per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "swift.proxy-server.container",
     "query": "SELECT mean(\"timing_count\") FROM \"swift.proxy-server.container\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'GET' AND \"returncode\" = '200' AND $timeFilter GROUP BY host, time($interval) fill(null)",
     "select": [
      [
       { "params": [ "timing_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "method", "operator": "=", "value": "GET" },
      { "condition": "AND", "key": "returncode", "operator": "=", "value": "200" },
      { "condition": "AND", "key": "metric_type", "operator": "=", "value": "counter" }
     ]
    }
   ]
  },
  {
   "title": "HEAD Count HTTP 204 per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"timing_count\") FROM \"swift.proxy-server.container\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'HEAD' AND \"returncode\" = '204' AND $timeFilter GROUP BY host, time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Proxy Server - Object", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "PUT Count HTTP 201 per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"timing_count\") FROM \"swift.proxy-server.object\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'PUT' AND \"returncode\" = '201' AND $timeFilter GROUP BY host, time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DELETE Count HTTP 204 per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"timing_count\") FROM \"swift.proxy-server.object\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'DELETE' AND \"returncode\" = '204' AND $timeFilter GROUP BY host, time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GET Count HTTP 200 per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"timing_count\") FROM \"swift.proxy-server.object\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'GET' AND \"returncode\" = '200' AND $timeFilter GROUP BY host, time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HEAD Count HTTP 200 per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"timing_count\") FROM \"swift.proxy-server.object\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'HEAD' AND \"returncode\" = '200' AND $timeFilter GROUP BY host,time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Proxy GETs (200) - Mean Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    {
     "format": "ms",
     "label": "Response Time (Lower is Better)"
    }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"timing_mean\")  FROM \"swift.proxy-server.object\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'GET' AND \"returncode\" = '200' AND $timeFilter GROUP BY host,time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Proxy GETs (200) - Low Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    {
     "format": "ms",
     "label": "Response Time (Lower is Better)"
    }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"timing_lower\") FROM \"swift.proxy-server.object\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'GET' AND \"returncode\" = '200' AND $timeFilter GROUP BY host,time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Proxy GETs (200) - High Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    {
     "format": "ms",
     "label": "Response Time (Lower is Better)"
    }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"timing_upper\") FROM \"swift.proxy-server.object\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'GET' AND \"returncode\" = '200' AND $timeFilter GROUP BY host,time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Proxy PUTs (201) - Mean Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    {
     "format": "ms",
     "label": "Response Time (Lower is Better)"
    }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"timing_mean\") FROM \"swift.proxy-server.object\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'PUT' AND \"returncode\" = '201' AND $timeFilter GROUP BY host,time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Proxy PUTs (201) - Low Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    {
     "format": "ms",
     "label": "Response Time (Lower is Better)"
    }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"timing_lower\") FROM \"swift.proxy-server.object\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'PUT' AND \"returncode\" = '201' AND $timeFilter GROUP BY host,time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Proxy PUTs (201) - High Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    {
     "format": "ms",
     "label": "Response Time (Lower is Better)"
    }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"timing_upper\") FROM \"swift.proxy-server.object\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'PUT' AND \"returncode\" = '201' AND $timeFilter GROUP BY host,time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Proxy Server - Object Aggregate Reads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 }
  },
  {
   "title": "Reads (GETs and HEADs) per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "GET RPS",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"timing_count\") FROM \"swift.proxy-server.object\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'GET' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "HEAD RPS",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"timing_count\") FROM \"swift.proxy-server.object\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'HEAD' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reads (GETs and HEADs) per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "rps", "label": "Throughput (Higher is Better)" }
   ],
   "targets": [
    {
     "alias": "GET RPS",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"timing_count\") FROM \"swift.proxy-server.object\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'GET' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "HEAD RPS",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"timing_count\") FROM \"swift.proxy-server.object\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'HEAD' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Proxy Server - Object Aggregate Writes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 }
  },
  {
   "title": "Writes (PUTs and DELETEs) Count HTTP 201, 204, 404, 503 per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "PUT-DELETE Aggregates",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"timing_count\") FROM \"swift.proxy-server.object\" WHERE \"metric_type\" = 'timing' AND (\"method\" = 'PUT' OR \"method\" = 'DELETE') AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Writes (PUTs and DELETEs) Count HTTP 201, 204, 404, 503 per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "wps", "label": "Throughput (Higher is Better)" }
   ],
   "targets": [
    {
     "alias": "PUT RPS",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"timing_count\") FROM \"swift.proxy-server.object\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'PUT' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "DELETE RPS",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"timing_count\") FROM \"swift.proxy-server.object\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'DELETE' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "DELETE Count HTTP 404 per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"timing_count\") FROM \"swift.proxy-server.object\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'DELETE' AND \"returncode\" = '404' AND $timeFilter GROUP BY host,time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GET Count HTTP 404 and 499 per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"timing_count\") FROM \"swift.proxy-server.container\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'GET' AND (\"returncode\" = '404' OR \"returncode\" = '499') AND $timeFilter GROUP BY time($interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HEAD Count HTTP 404 per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"timing_count\") FROM \"swift.proxy-server.object\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'HEAD' AND \"returncode\" = '404' AND $timeFilter GROUP BY host,time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PUT Count HTTP 503 per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"timing_count\") FROM \"swift.proxy-server.object\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'PUT' AND \"returncode\" = '503' AND $timeFilter GROUP BY host,time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DELETE Count HTTP 503 per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"timing_count\") FROM \"swift.proxy-server.object\" WHERE \"metric_type\" = 'timing' AND \"method\" = 'DELETE' AND \"returncode\" = '503' AND $timeFilter GROUP BY host,time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}