{
 "title": "Service - HAProxy metrics",
 "description": "HAProxy runtime metrics",
 "tags": [
  "haproxy",
  "influxdb",
  "telegraf"
 ],
 "time": { "from": "now-3h", "to": "now-1m" },
 "refresh": "20s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Hosts",
    "query": "SHOW TAG VALUES FROM \"haproxy\" WITH KEY = \"host\""
   },
   {
    "name": "frontend",
    "label": "Frontends",
    "query": "SHOW TAG VALUES FROM \"haproxy\" WITH KEY = \"proxy\""
   },
   {
    "name": "backend",
    "label": "Backends",
    "query": "SHOW TAG VALUES FROM \"haproxy\" WITH KEY = \"proxy\""
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "10s, 30s, 1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "General Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Backend HTTP errors",
   "type": "singlestat",
   "description": "HTTP 5xx request errors 1 minute rate of change over the last 15 minutes",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(((last(\"http_response.5xx\") + last(\"http_response.4xx\")) / 2)) FROM \"haproxy\" WHERE \"host\" =~ /^aio1$/ AND \"sv\" = 'BACKEND' GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average requests queue time",
   "type": "singlestat",
   "description": "The average requests queue time 1 minute derivative over the last 15 minutes.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"qtime\") FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"sv\" = 'BACKEND' GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Backend connections waiting",
   "type": "singlestat",
   "description": "Number of connections awaiting assignment to a backend server over the last 15 minutes",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"qcur\") FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"sv\" = 'BACKEND' GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of backends in error",
   "type": "singlestat",
   "description": "Number of backend which status is different than 'UP'",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") FROM (SELECT last(status) as \"status\" FROM \"haproxy\" WHERE \"type\" = 'server' AND \"status\" != 'UP' GROUP BY time($interval), \"proxy\") fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Frontend requests errors",
   "type": "singlestat",
   "description": "Frontend requests errors 1m rate of change over the last15 minutes.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(max(\"ereq\"), 1s) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"sv\" = 'FRONTEND' GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Frontend denied requests",
   "type": "singlestat",
   "description": "Frontend denied requests 1m rate of change over the last 15 minutes.",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT derivative(max(\"dreq\"), 1s) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"sv\" = 'FRONTEND' GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Frontend Sessions Usage",
   "type": "singlestat",
   "description": "Number of sessions used in percent of total number of sessions available over the last 15 min.",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 7 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ((max(\"scur\") / last(\"slim\")) * 100) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"sv\" = 'FRONTEND' GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of frontend in error",
   "type": "singlestat",
   "description": "Number of frontends which status is different than 'OPEN'",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") FROM (SELECT last(status) as \"status\" FROM \"haproxy\" WHERE \"type\" = 'frontend' AND \"status\" != 'OPEN' GROUP BY time($interval), \"proxy\") fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Frontend Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Frontends current status",
     "type": "table",
     "description": "A status different than 'OPEN' should be acted upon",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"frontend\", \"status\", \"host\" FROM (SELECT last(status) as \"status\", \"proxy\" as \"frontend\", \"sv\" as \"sv\", \"host\" as \"host\" FROM \"haproxy\" WHERE \"type\" = 'frontend' GROUP BY \"proxy\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Sessions rate",
     "type": "graph",
     "description": "Number of sessions created per second",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_proxy",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "haproxy",
       "options": {
        "showDisabledItems": false
       },
       "query": "SELECT mean(\"rate\") FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$frontend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
       "select": [
        [
         { "params": [ "rate" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
        { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
       ]
      }
     ]
    },
    {
     "title": "HTTP requests rate",
     "type": "graph",
     "description": "Number of HTTP requests / sec",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_proxy",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "haproxy",
       "options": {
        "showDisabledItems": false
       },
       "query": "SELECT mean(\"req_rate\") FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$frontend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
       "select": [
        [
         { "params": [ "req_rate" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
        { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
       ]
      }
     ]
    },
    {
     "title": "Bytes received rate",
     "type": "graph",
     "description": "Number of bytes received / sec",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_proxy",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(last(\"bin\")) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$frontend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HTTP responses",
     "type": "graph",
     "description": "Number of HTTP responses / sec",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col: $tag_proxy",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "proxy" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "haproxy",
       "options": {
        "showDisabledItems": false
       },
       "query": "SELECT derivative(last(\"http_response.1xx\")) AS \"http 1xx\" FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$frontend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
       "select": [
        [
         { "params": [ "ereq" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
        { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
       ]
      },
      {
       "alias": "$col: $tag_proxy",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "proxy" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "haproxy",
       "options": {
        "showDisabledItems": false
       },
       "query": "SELECT derivative(last(\"http_response.2xx\")) AS \"http 2xx\" FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$frontend$/ AND $timeFilter GROUP BY time($interval), \"proxy\" ",
       "select": [
        [
         { "params": [ "ereq" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
        { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
       ]
      },
      {
       "alias": "$col: $tag_proxy",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "proxy" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "haproxy",
       "options": {
        "showDisabledItems": false
       },
       "query": "SELECT derivative(last(\"http_response.3xx\")) AS \"http 3xx\" FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$frontend$/ AND $timeFilter GROUP BY time($interval), \"proxy\" ",
       "select": [
        [
         { "params": [ "ereq" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
        { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
       ]
      },
      {
       "alias": "$col: $tag_proxy",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "proxy" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "haproxy",
       "options": {
        "showDisabledItems": false
       },
       "query": "SELECT derivative(last(\"http_response.4xx\")) AS \"http 4xx\" FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$frontend$/ AND $timeFilter GROUP BY time($interval), \"proxy\" ",
       "select": [
        [
         { "params": [ "ereq" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
        { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
       ]
      },
      {
       "alias": "$col: $tag_proxy",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "proxy" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "haproxy",
       "options": {
        "showDisabledItems": false
       },
       "query": "SELECT derivative(last(\"http_response.5xx\")) AS \"http 5xx\" FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$frontend$/ AND $timeFilter GROUP BY time($interval), \"proxy\" ",
       "select": [
        [
         { "params": [ "ereq" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
        { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
       ]
      }
     ]
    },
    {
     "title": "Requests denied rate",
     "type": "graph",
     "description": "Requests denied because of security concerns.\n- For tcp this is because of a matched tcp\n  request content rule.\n- For http this is because of a matched http\n  request or tarpit rule.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_proxy",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "proxy" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "haproxy",
       "options": {
        "showDisabledItems": false
       },
       "query": "SELECT derivative(last(\"dreq\")) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$frontend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
       "select": [
        [
         { "params": [ "ereq" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
        { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
       ]
      }
     ]
    },
    {
     "title": "Bytes sent rate",
     "type": "graph",
     "description": "Number of bytes sent  /sec",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_proxy",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(last(\"bout\")) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$frontend$/ AND $timeFilter GROUP BY time($interval), \"proxy\" ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Requests errors rate",
     "type": "graph",
     "description": "Request errors. Some of the possible causes are:\n- early termination from the client, before the\n  request has been sent.\n- read error from the client\n   - client timeout\n   - client closed connection\n   - various bad requests from the client.\n   - request was tarpitted.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_proxy",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "proxy" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "haproxy",
       "options": {
        "showDisabledItems": false
       },
       "query": "SELECT derivative(last(\"ereq\")) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$frontend$/ AND $timeFilter GROUP BY time($interval), \"proxy\" ",
       "select": [
        [
         { "params": [ "ereq" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
        { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Backend Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backends current status",
     "type": "table",
     "description": "A status different than 'UP' should be acted upon",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"proxy\", \"status\", \"check_status\", \"sv\", \"host\" FROM (SELECT last(status) as \"status\", \"proxy\" as \"proxy\", \"check_status\" as \"check_status\", \"sv\" as \"sv\", \"host\" as \"host\" FROM \"haproxy\" WHERE \"type\" = 'server' GROUP BY \"proxy\")",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Byes received rate",
     "type": "graph",
     "description": "Number of bytes received by the backends / sec",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_proxy",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(last(\"bin\")) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HTTP responses rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col: $tag_proxy",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "proxy" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "haproxy",
       "options": {
        "showDisabledItems": false
       },
       "query": "SELECT derivative(last(\"http_response.1xx\")) AS \"http 1xx\" FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
       "select": [
        [
         { "params": [ "ereq" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
        { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
       ]
      },
      {
       "alias": "$col: $tag_proxy",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "proxy" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "haproxy",
       "options": {
        "showDisabledItems": false
       },
       "query": "SELECT derivative(last(\"http_response.2xx\")) AS \"http 2xx\" FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
       "select": [
        [
         { "params": [ "ereq" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
        { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
       ]
      },
      {
       "alias": "$col: $tag_proxy",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "proxy" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "haproxy",
       "options": {
        "showDisabledItems": false
       },
       "query": "SELECT derivative(last(\"http_response.3xx\")) AS \"http 3xx\" FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
       "select": [
        [
         { "params": [ "ereq" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
        { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
       ]
      },
      {
       "alias": "$col: $tag_proxy",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "proxy" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "haproxy",
       "options": {
        "showDisabledItems": false
       },
       "query": "SELECT derivative(last(\"http_response.4xx\")) AS \"http 4xx\" FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
       "select": [
        [
         { "params": [ "ereq" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
        { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
       ]
      },
      {
       "alias": "$col: $tag_proxy",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "proxy" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "haproxy",
       "options": {
        "showDisabledItems": false
       },
       "query": "SELECT derivative(last(\"http_response.5xx\")) AS \"http 5xx\" FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
       "select": [
        [
         { "params": [ "ereq" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
        { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
       ]
      }
     ]
    },
    {
     "title": "Average response time (ms)",
     "type": "graph",
     "description": "Average backend response time (in ms) for the last 1,024 requests",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_proxy",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "proxy" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "haproxy",
       "options": {
        "showDisabledItems": false
       },
       "query": "SELECT mean(\"rtime\") FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
       "select": [
        [
         { "params": [ "rtime" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
        { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
       ]
      }
     ]
    },
    {
     "title": "Bytes sent rate",
     "type": "graph",
     "description": "Number of bytes sent / sec by the backends",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_proxy",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT derivative(last(\"bout\")) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Average queue time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_proxy",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "proxy" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "haproxy",
       "options": {
        "showDisabledItems": false
       },
       "query": "SELECT last(\"qtime\") FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
       "select": [
        [
         { "params": [ "qtime" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
        { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
       ]
      }
     ]
    },
    {
     "title": "Backend requests denied rate",
     "type": "graph",
     "description": "Number of requests that encountered an error attempting to connect to a backend server",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_proxy",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "proxy" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "haproxy",
       "options": {
        "showDisabledItems": false
       },
       "query": "SELECT derivative(last(\"econ\")) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\" ",
       "select": [
        [
         { "params": [ "econ" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
        { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
       ]
      }
     ]
    },
    {
     "title": "Responses denied rate",
     "type": "graph",
     "description": "Responses denied due to security raisons (ACL-restricted)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_proxy",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "proxy" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "haproxy",
       "options": {
        "showDisabledItems": false
       },
       "query": "SELECT derivative(last(\"dresp\")) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
       "select": [
        [
         { "params": [ "dresp" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
        { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
       ]
      }
     ]
    },
    {
     "title": "Backend failed requests rate",
     "type": "graph",
     "description": "Rate of requests whose responses yielded an error",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_proxy",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "proxy" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "haproxy",
       "options": {
        "showDisabledItems": false
       },
       "query": "SELECT derivative(last(\"eresp\")) FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
       "select": [
        [
         { "params": [ "eresp" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
        { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
       ]
      }
     ]
    },
    {
     "title": "Backend redispatch rate",
     "type": "graph",
     "description": "Number of times a request was redispatched to a different backend",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_proxy",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "proxy" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "haproxy",
       "options": {
        "showDisabledItems": false
       },
       "query": "SELECT last(\"wredis\") FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
       "select": [
        [
         { "params": [ "eresp" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
        { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
       ]
      }
     ]
    },
    {
     "title": "Backend connection retries",
     "type": "graph",
     "description": "Number of times a connection was retried",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_proxy",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "proxy" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "haproxy",
       "options": {
        "showDisabledItems": false
       },
       "query": "SELECT last(\"wretr\") FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\"",
       "select": [
        [
         { "params": [ "eresp" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
        { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
       ]
      }
     ]
    },
    {
     "title": "Number of requests unassigned",
     "type": "graph",
     "description": "Current number of requests unassigned in queue",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_proxy",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "proxy" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "haproxy",
       "options": {
        "showDisabledItems": false
       },
       "query": "SELECT last(\"qcur\") FROM \"haproxy\" WHERE \"host\" =~ /^$host$/ AND \"proxy\" =~ /^$backend$/ AND $timeFilter GROUP BY time($interval), \"proxy\" fill(null)",
       "select": [
        [
         { "params": [ "qtime" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "proxy", "operator": "=~", "value": "/^$proxy$/" },
        { "condition": "AND", "key": "sv", "operator": "=~", "value": "/^$sv$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}